package org.nsu.fit.tests.api;

import io.qameta.allure.Feature;
import io.qameta.allure.Severity;
import io.qameta.allure.SeverityLevel;
import org.nsu.fit.services.rest.data.AccountTokenPojo;
import org.nsu.fit.services.rest.data.CustomerPojo;
import org.nsu.fit.services.rest.data.PlanPojo;
import org.nsu.fit.services.rest.data.SubscriptionPojo;
import org.testng.annotations.Test;

import javax.ws.rs.BadRequestException;

public class BadSubscription implements TestInterface {
    private SubscriptionPojo subscription;

    @Test(description = "Create subscription.", expectedExceptions = { BadRequestException.class })
    @Severity(SeverityLevel.CRITICAL)
    @Feature("Subscription feature.")
    public void trashTheSubscription() {
        PlanPojo plan = client.createPlan(adminToken);
        CustomerPojo customer = client.createAutoGeneratedCustomer(adminToken);
        AccountTokenPojo customerToken = client.authenticate(customer.login, customer.pass);
        subscription = client.createBadSubscription(customerToken, plan, customer);
    }
}
